print(" ")
print("  -Postres = 01")
print("  -Carnes = 02")
print("  -Pescados = 03")
print("  -Pasta = 04")
print("  -Arroces = 05")
print("  -Salsas = 06")
print(" ")
Elección_1 = input("  Elija el número del tipo de recetas que desea obtener: ")

if Elección_1 == str(1):
    #Postres
    print(" ")
    print("  Listado de recetas: ")
    print("  01 = Bizcocho de yogur ")
    print("  02 = Gofres ")
    print("  03 = Natillas")
    print(" ")

Elección_Elegida = input("  Inserte el número de la receta que desea mostrar: ")

if Elección_Elegida == str(1):
    print(" ")
    print("  BIZCOCHO DE YOGUR PARA 4 PERONAS:  ")
    print("  Ingredientes: ")
    print("  3 huevos")
    print("  1 yogur natural (No tirar el envase)")
    print("  Azúcar")
    print("  Harina de trigo")
    print("  Levadura en polvo")
    print("  Aceite de girasol")
    print("  Un bol o plato sopero")
    print(" ")
    print("  Realización: ")
    print("  1. En primer lugar coge el plato o bol y añade los 6 huevos  y el yogur (no tirar el envase.) ")
    print("  2. Rellena el envase del yogur con el azúcar, ya que esa será la medida, y viértelo en el bol.")
    print("  3. Repite el paso 2 pero ahora con la harina, con la harina tendrás que rellenar el envase enved de 1 vez 3, y echarlo")
    print("  en el bol.")
    print("  4. De nuevo repite el paso 2 y 3 pero ahora con el aceite y la cantidad será medio vaso. ")
    print("  5. Por último echa la levadura, y ponlo en el horno a 180 grados y espera a que esté doradito.")
    print(" ")

if Elección_Elegida == str(2):
    print(" ")
    print("  GOFRES PARA 6 PERSONAS: ")
    print("  Ingredientes: ")
    print("  300 g de harina")
    print("  ½ litro de leche")
    print("  70 g de azúcar")
    print("  100 g de mantequilla")
    print("  2 huevos")
    print("  1 sobre de levadura")
    print("  Une pizca de sal")
    print(" ")
    print("  Realización: ")
    print("  1. Corta la mantequilla en trocitos y ponlos en un cazo a fuego lento para que se funda.")
    print("  2. Rompe los huevos y bátelos en una fuente a continuación vierte la leche, el azúcar y la mantequilla fundida.")
    print("  3. Añade la harina poco a poco y bate entre cucharada y cucharada.")
    print("  4. Por último vierte la masa en una gofrera y dejalo un minutillo.")
    print(" ")

if Elección_Elegida == str(3):
    print(" ")
    print("  NATILLAS PARA 8 PERSONAS: ")
    print("  Ingredientes: ")
    print("  1 Sobre de flanín")
    print("  8 Cucharadas de azúcar")
    print("  1L de leche")
    print(" ")
    print("  Realización: ")
    print("  1. Disolver todos los ingredientes en la leche en frio.")
    print("  2. Llevar a ebullición, dejar cocinar por espacio de 1 minuto sin dejar de remover.")
    print("  3. Retirar del fuego, repartirlo en 8 tazas y dejarlo enfriar entr 1-3h.")
    print(" ")

input()