print(" ")
Contraseña = input("Por favor, inserte la contraseña: ")

def Mostrar_Diario():
    print(" ")
    print("MI DIARIO: ")
    print("Día 22/8/2022")
    print("Bueno, empezamos nuestro diario en casa. ")
    print("En este verano nos pusimos con las reformas de las habitaciones mia y de mi  ")
    print("hermana, y hoy como ya tenemos mi cama en la habitación fuimos avanzando Bastante,")
    print("colocamos mis cosas en mi habitación y las de mi hermana en la suya movimos un par")
    print("de estanterias y ya por hoy listo.")
    print("A por cierto seme olvidó decir que fuí con Marcos a Friol a dormir")
    print(" ")
    print("Día 23/8/2022")
    print("Al día siguiente cuando me desperte desayunamos y Marcos y yo jugamos un poco. Hasta")
    print("que llegaron Lucía con sus amigas, que las había invitado porque tenía ganas de que ")
    print("fueran. Nos bañamos en la piscina, comimos comida de cumpleaños, y lo más emocionante")
    print("fué cuando a la noche tiramos fuegos artificiales de colores. ")
    print("Ya cuando nos ibámos a Lugo Fiti convenció a mi madre de que me quedara otra vez a")
    print("dormir. ")
    print(" ")
    print("Día 24/8/2022")
    print("Hoy cuando me desperte Marcos, Fiti y yo estubimoos un rato con la tablet y el móvil.")
    print("Tambien a la mañana nos dimos un chapuzón antes de comer. Por la tarde fuimos a cojer")
    print("moras hasta que ya nos vinimos a Lugo sobre las 21:30.")
    print(" ")
    print("Día 25/8/2022")
    print("Bueno, ya estamos todos en Lugo. Hoy por la mañana mamá y papá fueron al Ceao a buscar")
    print("los muebles de las habitaciones, pero cundo llegaron le dijeron que aun no habian llegado.")
    print("pero despues de comer fuimos con Matías y la madrina a buscar judías a casa de la abuela,")
    print("y después sobre las siete y media ocho papá y mamá volvieron, pero esta vez le dijeron")
    print("que cerraba a las 19:00 entonces esperamos al día siguiente.")
    print(" ")
    print("Día 26/8/2022")
    print("Hoy por la mañana sobre las 12:00 fimos a casa de la Abuela y al centro comercial Family")
    print("a comprar vino porque el sábado vamos a hacer una primada con la tía Consuelo en Bacurín.")
    print("después fuimos a casa a comer y sobre las 16:30 mamá y papá fueron a por los muebles, esta")
    print("vez si que los recojieron. Llegamos a casa y primero montamos la mesa y despues la cama, la")
    print("cama nos llevó más de 3h pero finalmente lo conseguimos, aunque esa noche Lucía no durmió")
    print("ahi porque papá se quedó un rato montando los cajones y nosotros ya estábamos en cama ")
    print("(porque nos mandaron).")
    print(" ")
    print("Día 27/8/2022")
    print("Bueno, hoy por la mañana hicimos lo de siempre: Jugar con la tablet, el ordenador,")
    print("aburrirnos... pero a la tarde bajamos al Flubial con  Matías. Y eso es todo.")
    print(" ")
    print("Día 27/8/2022")
    print("Hoy por la mañana sobre la 13:30 como ya os conte fuimos a Bacurín comimos y cenamos allí")
    print("fué casi toda la familia de mamá y también de primos Marcos, Matias y Natalia.")
    print("Jugamos con la pelota y con León, también fuimos a dar un paseo con los primos y con Uxía hasta")
    print("La Ponte de San Miguel y León y Sheila como hacia tanto calor y tenian sed ellos se bañaron")
    print("aunque a nosotros nos dieron un poquite de envidia nos lo pasamos bien igual.")
    print("También cuando llegamos estubimos con Alexa el asistente de Amazon. Y finalmente cuando")
    print("nos íbamos a ir Uxía, Lucía y yo convencimos a papá y mamá de que nos quedáramos a cenar.")
    print(" ")   

if Contraseña == str(7412369):
    Mostrar_Diario()

input()